### ISSUE TITLE
BUG: sh metracer.sh -v 30899 "MoreTools|Account" "init"

### ISSUE THREAD

**Issue by mikelaud** [kocherovms/metracer#23]
# sh metracer.sh -v 30899 "MoreTools|Account" "init"
Attached to JVM (PID 30899)
Management agent is running
Connected to MBean server
metracer agent is running
Detached from JVM (PID 30899)
Class matching pattern set to "MoreTools|Account"
Method matching pattern set to "init"
Failed to start listening to agent events: Error unmarshaling return; nested exception is:
        java.io.EOFException
java.lang.RuntimeException: Failed to start listening to agent events: Error unmarshaling return; nested exception is:
        java.io.EOFException
        at com.develorium.metracer.Main.startListeningToAgentEvents(Main.java:188)
        at com.develorium.metracer.Main.execute(Main.java:56)
        at com.develorium.metracer.Main.main(Main.java:37)
Caused by: java.rmi.UnmarshalException: Error unmarshaling return; nested exception is:
        java.io.EOFException
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:246)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
        at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
        at javax.management.remote.rmi.RMIConnectionImpl_Stub.addNotificationListeners(Unknown Source)
        at javax.management.remote.rmi.RMIConnector.addListenersWithSubjects(RMIConnector.java:602)
        at javax.management.remote.rmi.RMIConnector.addListenerWithSubject(RMIConnector.java:577)
        at javax.management.remote.rmi.RMIConnector.access$700(RMIConnector.java:121)
        at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.addNotificationListener(RMIConnector.java:1246)
        at com.develorium.metracer.Main.startListeningToAgentEvents(Main.java:180)
        ... 2 more
Caused by: java.io.EOFException
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2598)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:244)
        ... 10 more

**Comment by mikelaud** [comment]
# java -version
java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) Server VM (build 24.55-b03, mixed mode)

**Comment by kocherovms** [comment]
Will be workarounded by try / catching
